# Generated by Django 6.0.2 on 2026-02-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_name', models.CharField(max_length=100)),
                ('flower_quantity', models.IntegerField()),
                ('flower_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
